### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by OwenBrotherwood** [exoplatform/platform-public-distributions#127]
I cannot find any license information for this repo.

**Comment by fdrouet** [comment]
You are totally right, the LICENSE file is missing at the root of the repo and it will be fixed soon. Thanks for the notification @OwenBrotherwood.

Take note that if you have a look at our source code header, you will see that everything is under LGPL license.

**Comment by mgreau** [comment]
The [LICENSE](https://github.com/exoplatform/platform-public-distributions/blob/develop/LICENSE) file (GNU Lesser General Public License v3.0) has been added to the repo.
